### ISSUE TITLE
Versions naming

### ISSUE THREAD

**Issue by siberianisaev** [GetAmbassador/ambassador-ios-pod#3]
Hello! I got that you pushed new [v1.0.12](https://github.com/CocoaPods/Specs/blob/358b510c5731abcbcf54fd15991d6e2ca54cf81c/Specs/8/0/a/Ambassador/1.0.12/Ambassador.podspec.json) to Trunk.
But `pod update` command download only [v1.0.70](https://github.com/GetAmbassador/ambassador-ios-pod/releases/tag/1.0.70). To fetch v1.0.12 client must use something like `pod 'Ambassador', :git => 'https://github.com/GetAmbassador/ambassador-ios-pod.git', :tag => '1.0.12'`
So Cocoapods decided that last release is 1.0.70 but not 1.0.12. Must be ascending order of versions there, tag 1.0.70 must be replaced with 1.0.7.

**Comment by forgingdestiny** [comment]
This is resolved.
